### ISSUE TITLE
CSS issues with some other plugins

### ISSUE THREAD

**Issue by nahuakang** [jonesmelton/logseq-tufte-theme#1]
Hey! Really like this theme so I tried it out already and found that some corner cases need ironing out. Reporting some screenshots so it might help make this theme even better :smiley: 

For example, I also use Awsesome UI/Awesome Styler, etc.

Currently Tufte renders:
- ![Screenshot from 2023-02-02 10-45-53](https://user-images.githubusercontent.com/18533347/216290529-adbb19a2-5f3c-4639-ad8f-e8812424683f.png)

Using Dev theme renders:
- ![Screenshot from 2023-02-02 10-47-31](https://user-images.githubusercontent.com/18533347/216290545-f838c927-25e5-4cd9-bada-4e19ff137eba.png)

**Comment by cliffordx** [comment]
I'm currently using it now. I see the same problem but I manage to disable the portion in tufte.css along number `147` Adds dark mode.
```
/* Adds dark mode */
@media (prefers-color-scheme: dark) {
    /* a:link, .tufte-underline, .hover-tufte-underline:hover {
        text-shadow: 0.03em 0 #151515, -0.03em 0 #151515, 0 0.03em #151515, 0 -0.03em #151515, 0.06em 0 #151515, -0.06em 0 #151515, 0.09em 0 #151515, -0.09em 0 #151515, 0.12em 0 #151515, -0.12em 0 #151515, 0.15em 0 #151515, -0.15em 0 #151515;
    } */
}
```

I made other hacks but so far I will be using this light theme for a long time. (I use another theme for dark theme). If this theme will have proper dark theme then it's a bonus.

**Comment by hungsu** [comment]
Hi @nahuakang , @cliffordx , I've made a pull request to fix the issue. Hope @jonesmelton  sees and accepts!
